### ISSUE TITLE
Write Code to Test Sensors

### ISSUE THREAD

**Issue by JuliusC4es4r** [Quadcopter-System-Solutions/Firmware#11]
Write separate code for testing sensors. Ensure that functions used in main code file are used in this folder to properly test those files. Make sure both sensors are initialized and print out their values to the serial port.

**Comment by JuliusC4es4r** [comment]
@cartercooper I pushed a folder called sensorTest that should be mostly what we need to test sensors next weekend. I ran into an issue with something on the gyroscope side about using u32*.  I also had issues with global variables again. Please take a look to see if thats what we exactly need.

**Comment by cartercooper** [comment]
I have fixed the things that you mentioned. For the gyro issue, I didn't make it clear that the getGyro and getAccel functions returned pointers to arrays of the 3 readings, one for each axis. Looking back, that was probably a bad idea in the first place so I have replaced those with structs to clear confusion. For the global variables, you just have to use the extern keyword when declaring them in a second file. You can see what I mean in the sensorTest file
